require 'pry'
require 'nokogiri'
require 'open-uri'

require_relative '../lib/soccerarticles/article'
require_relative '../lib/soccerarticles/cli'
require_relative '../lib/soccerarticles/ScraperSpain'
require_relative '../lib/soccerarticles/ScraperEngland'
require_relative '../lib/soccerarticles/ScraperFrance'
require_relative '../lib/soccerarticles/ScraperItaly'
require_relative '../lib/soccerarticles/ScraperGermany'
