require 'pry'
require 'nokogiri'
require 'open-uri'

#require_relative '../lib/article'
require_relative '../lib/cli'
require_relative '../lib/ScraperSpain'
require_relative '../lib/ScraperEngland'
require_relative '../lib/ScraperFrance'
require_relative '../lib/ScraperItaly'
require_relative '../lib/ScraperGermany'
require_relative '../lib/version'
